### ISSUE TITLE
Padding of list elements is too large in theme_boost on Moodle version 3.2

### ISSUE THREAD

**Issue by Kathrin84** [University-of-Strathclyde-LTE-Team/moodle-atto_morebackcolors#7]
Hi,
I'm testing our plugins for the new theme Boost with Moodle verison 3.2 and there the padding of your background list elements is too large:
![morebackcolors_boost](https://cloud.githubusercontent.com/assets/4711883/24286375/3afde00a-1075-11e7-994f-27ec843d9046.png)
Best regards, Kathrin

**Comment by ndunand** [comment]
This is now fixed in the new plugin version.
